replicaCount: 1
image:
  repository: harbor.voidbox.io/loneexile/frontend-demo
  pullPolicy: IfNotPresent
  tag: "15"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
env:
  PUBLIC_BACKEND_URL: backend-demo.default.svc.cluster.local/
service:
  type: ClusterIP
  port: 80
  targetPort: 80
  nodePort: null
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
